#!/bin/sh

cd ~

#export QT_AUTO_SCREEN_SCALE_FACTOR=1
#export QT_QPA_PLATFORM="wayland;xcb"
#export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
#export QT_QPA_PLATFORMTHEME=qt5ct

##export SDL_VIDEODRIVER=wayland
#export _JAVA_AWT_WM_NONEREPARENTING=1
#export CLUTTER_BACKEND="wayland"
#export GDK_BACKEND="wayland,x11"

#export GTK_THEME="Catppuccin-Mocha-Standard-Teal-Dark"

#export XCURSOR_THEME=ArcMidnight-cursors
#export XCURSOR_SIZE=24

#export MOZ_ENABLE_WAYLAND=1

exec Hyprland
